### ISSUE TITLE
Cannot find module 'builtin-pages-lib'

### ISSUE THREAD

**Issue by dsun29** [beakerbrowser/beaker#694]
Operation System: CentOS 7.3
Beaker Version: latest
Node: 8.6

Error message from both `npm run rebuild` and `npm run burnthemall`

```
Error: Cannot find module 'builtin-pages-lib' from '/root/beaker/app/builtin-pages/views'
    at /root/beaker/node_modules/browserify/node_modules/browser-resolve/node_modules/resolve/lib/async.js:46:17
    at process (/root/beaker/node_modules/browserify/node_modules/browser-resolve/node_modules/resolve/lib/async.js:173:43)
    at ondir (/root/beaker/node_modules/browserify/node_modules/browser-resolve/node_modules/resolve/lib/async.js:188:17)
    at load (/root/beaker/node_modules/browserify/node_modules/browser-resolve/node_modules/resolve/lib/async.js:69:43)
    at onex (/root/beaker/node_modules/browserify/node_modules/browser-resolve/node_modules/resolve/lib/async.js:92:31)
    at /root/beaker/node_modules/browserify/node_modules/browser-resolve/node_modules/resolve/lib/async.js:22:47
    at FSReqWrap.oncomplete (fs.js:153:21)

```

**Comment by pfrazee** [comment]
For this to have happened, npm must have failed to install a dependency that's included via github. (If you look in `./app/package.json` you'll see the definition.) Any idea why that might have happened?

**Comment by pfrazee** [comment]
Your other comment gives a hint of the problem https://github.com/beakerbrowser/beaker/issues/587#issuecomment-335051260

`builtin-pages-lib` is not published on the npm registry, you need to install what's in the package.json

**Comment by dsun29** [comment]
I made beakerbrowser work in my OpenSuse42.2 (Node V6.11). However I cannot make it work in CentOS (Node V8.3). In CentOS it says when running `npm install`
`lifecycle beakerbrowser@~postinstall: cannot run in wd %s %s (wd=%s) beakerbrowser@ cd app && npm install /root/beaker`

**Comment by pfrazee** [comment]
Hm. I'll copy that into the other issue.
